language: python
jobs:
  include:
    - name: "Python 3.9 on Linux Bionic"
      os: linux
      dist: "bionic"
      python: "3.9"
    - name: "Python 3.8 on Linux Bionic"
      os: linux
      dist: "bionic"
      python: "3.8"
    - name: "Python 3.7 on Linux Bionic"
      os: linux
      dist: "bionic"
      python: "3.7"
    - name: "Python 3.6 on Linux Bionic"
      os: linux
      dist: "bionic"
      python: "3.6"
    - name: "Python 3.9 on OSX"
      os: osx
      osx_image: xcode11.4
      language: generic
      env: TOXENV=py39
    - name: "Python 3.8 on OSX"
      os: osx
      osx_image: xcode11.4
      language: generic
      env: TOXENV=py38
    - name: "Python 3.7 on OSX"
      os: osx
      osx_image: xcode11.4
      language: generic
      env: TOXENV=py37
    - name: "Python 3.6 on OSX"
      os: osx
      osx_image: xcode11.4
      language: generic
      env: TOXENV=py36

before_install:
  - chmod +x ./.travis/install.sh

install:
  - "./.travis/install.sh"

notifications:
  email: false

script:
  - coverage run -m unittest cpp_faster_fifo/tests/test_faster_fifo.py

after_success:
  - bash <(curl -s https://codecov.io/bash)
